"use client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { factStatuses, factStatusLabels, imageKindLabels, type Editorial, type EditorialImage, type FactStatus } from "@/lib/editorial";
const selectStyle="block h-10 w-full rounded-md border bg-background px-3 py-0 text-sm";
export function SaintEditorialFields({value,onChange}:{value:Editorial;onChange:(value:Editorial)=>void}) {
  const set=<K extends keyof Editorial>(key:K,next:Editorial[K])=>onChange({...value,[key]:next});
  return <fieldset className="space-y-4 border rounded-lg p-4"><legend className="px-2 font-semibold">Fuentes y estado de los datos</legend>
    <Label htmlFor="entity-kind">Tipo de identidad</Label><select id="entity-kind" className={selectStyle} value={value.kind} onChange={e=>set("kind",e.target.value as Editorial["kind"])}><option value="person">Persona</option><option value="archangel">Arcángel</option><option value="collective">Grupo colectivo</option></select>
    <Label htmlFor="ecclesial-status">Tratamiento eclesiástico documentado</Label><Input id="ecclesial-status" value={value.ecclesialStatus} onChange={e=>set("ecclesialStatus",e.target.value)}/>
    {(["birthDate","deathDate"] as const).map(key=><div key={key} className="space-y-2"><Label htmlFor={key+"-text"}>{key==="birthDate"?"Fecha de nacimiento documentada":"Fecha de fallecimiento documentada"}</Label><Input id={key+"-text"} value={value[key].text??""} onChange={e=>set(key,{...value[key],text:e.target.value||null})}/><Label htmlFor={key+"-status"}>Estado de {key==="birthDate"?"nacimiento":"fallecimiento"}</Label><select id={key+"-status"} className={selectStyle} value={value[key].status} onChange={e=>set(key,{...value[key],status:e.target.value as FactStatus})}>{factStatuses.map(status=><option key={status} value={status}>{factStatusLabels[status]}</option>)}</select></div>)}
    <Label htmlFor="birthplace-status">Estado del lugar de nacimiento</Label><select id="birthplace-status" className={selectStyle} value={value.birthplaceStatus} onChange={e=>set("birthplaceStatus",e.target.value as FactStatus)}>{factStatuses.map(status=><option key={status} value={status}>{factStatusLabels[status]}</option>)}</select>
    <Label htmlFor="editorial-notes">Notas sobre límites y tradiciones</Label><textarea id="editorial-notes" className="min-h-24 w-full rounded-md border bg-background p-3" value={value.notes??""} onChange={e=>set("notes",e.target.value||null)}/>
    {value.sources.map((source,index)=><fieldset key={index} className="space-y-2 rounded border p-3"><legend>Fuente {index+1}</legend>{([['url','URL'],['institution','Institución o autor'],['title','Título'],['accessedAt','Consulta (AAAA-MM-DD)']] as const).map(([key,label])=><div key={key}><Label htmlFor={`source-${index}-${key}`}>{label}</Label><Input id={`source-${index}-${key}`} value={source[key]} onChange={e=>set("sources",value.sources.map((s,i)=>i===index?{...s,[key]:e.target.value}:s))}/></div>)}<Label htmlFor={`source-${index}-claims`}>Afirmaciones sustentadas (una por línea)</Label><textarea id={`source-${index}-claims`} className="min-h-24 w-full rounded border bg-background p-3" value={source.claims.join("\n")} onChange={e=>set("sources",value.sources.map((s,i)=>i===index?{...s,claims:e.target.value.split("\n")}:s))}/><Button type="button" variant="outline" onClick={()=>set("sources",value.sources.filter((_,i)=>i!==index))}>Quitar fuente {index+1}</Button></fieldset>)}
    <Button type="button" variant="outline" disabled={value.sources.length>=20} onClick={()=>set("sources",[...value.sources,{url:"",institution:"",title:"",accessedAt:new Date().toISOString().slice(0,10),claims:[]}])}>Añadir fuente</Button>
    <fieldset className="space-y-2 rounded border p-3"><legend>Imagen y licencia</legend>{value.image?<>{([['sourceUrl','Página de procedencia'],['creator','Autor de la imagen'],['license','Licencia o dominio público'],['licenseUrl','URL de licencia o fundamento'],['attribution','Atribución'],['alt','Texto alternativo']] as const).map(([key,label])=><div key={key}><Label htmlFor={`image-${key}`}>{label}</Label><Input id={`image-${key}`} value={value.image![key]} onChange={e=>set("image",{...value.image!,[key]:e.target.value})}/></div>)}<Label htmlFor="image-kind">Tipo de imagen</Label><select id="image-kind" className={selectStyle} value={value.image.kind} onChange={e=>set("image",{...value.image!,kind:e.target.value as EditorialImage["kind"]})}>{Object.entries(imageKindLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><Button type="button" variant="outline" onClick={()=>set("image",null)}>Quitar datos de imagen</Button></>:<Button type="button" variant="outline" onClick={()=>set("image",{sourceUrl:"",creator:"",license:"",licenseUrl:"",attribution:"",alt:"",kind:"painting"})}>Documentar imagen</Button>}</fieldset>
  </fieldset>;
}
